name: VPERESTART
main: iJoshuaHD\iMCPE\ASR\Loader
version: 2.0.3
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: STARTUP
author: iJoshuaHD
description: Restarts your server at given interval.
website: https://github.com/iJoshuaHD/ASR
commands:
 asr:
  description: "Set ASR Time"
  permission: asr.command.asr
 restart:
  description: "Check ASR Status"
  permission: asr.command.restart
permissions:
 asr.command.asr:
  description: "Usage: /asr <value>"
  default: op
 asr.command.restart:
  description: "Usage: /restart"
  default: true
